apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: vault-ca
spec:
  sources:
  - configMap:
      name: vault-ca
      key: ca.crt
  target:
    configMap:
      key: root-ca.pem
