apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxpi
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxpi
  template:
    metadata:
      labels:
        app: proxpi
    spec:
      containers:
      - name: proxpi
        image: epicwink/proxpi:1.3.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 5000
        env:
        - name: PROXPI_CACHE_DIR
          value: "/var/cache/proxpi"
        volumeMounts:
        - name: cache-volume
          mountPath: /var/cache/proxpi
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache-volume
        persistentVolumeClaim:
          claimName: proxpi-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxpi-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: proxpi
  namespace: tools
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: proxpi
