apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: database
data:
  init-dbs.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER authentik WITH PASSWORD '${POSTGRES_PASSWORD}';
        CREATE DATABASE authentik OWNER authentik;
        CREATE USER grafana WITH PASSWORD '${POSTGRES_PASSWORD}';
        CREATE DATABASE grafana OWNER grafana;
        CREATE USER openfga WITH PASSWORD '${POSTGRES_PASSWORD}';
        CREATE DATABASE openfga OWNER openfga;
        CREATE USER gitea WITH PASSWORD '${POSTGRES_PASSWORD}';
        CREATE DATABASE gitea OWNER gitea;
    EOSQL

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 70
      containers:
      - name: postgres
        image: postgres:16-alpine
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 70
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-vault-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init-dbs.sh
          subPath: init-dbs.sh
        - name: postgres-run
          mountPath: /var/run/postgresql
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
      - name: postgres-run
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
