apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "65"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: manifests/gitea-runner
    helm:
      values: |
        baseDomain: {{ .Values.baseDomain }}

    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
