apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vaults
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'ghcr.io/bank-vaults/helm-charts'
    chart: vault-operator
    targetRevision: 1.21.0 # The migration to ghcr.io preserves versions
    helm:
      values: |
        # Helm values for Bank-Vaults operator if needed
        # By default, it runs with sensible defaults in its own namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
