apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.goauthentik.io'
    chart: authentik
    targetRevision: 2026.5.3
    helm:
      values: |
        authentik:
          secret_key: ""
          postgresql:
            host: postgres.database.svc.cluster.local
            name: authentik
            user: authentik
            password: ""
          redis:
            host: redis.database.svc.cluster.local

        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-vault-secrets
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-vault-secrets
                  key: AUTHENTIK_POSTGRESQL__PASSWORD

        # Disable bundled postgres/redis since we provide our own
        postgresql:
          enabled: false
        redis:
          enabled: false
          
        server:
          # Mount the blueprint
          extraVolumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          extraVolumeMounts:
            - name: blueprints
              mountPath: /media/blueprints

        worker:
          extraVolumes:
            - name: blueprints
              configMap:
                name: authentik-blueprints
          extraVolumeMounts:
            - name: blueprints
              mountPath: /media/blueprints
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-blueprints
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "44" # Before Authentik
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: manifests/authentik
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
