apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxpi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "63"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: argo/manifests/proxpi
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
